--CHECKING DATA
SELECT COUNT(*)
FROM 
Blinkit_data

--SOME NEEDFUL DATA CLEANING

UPDATE Blinkit_data
SET Item_Fat_Content =
CASE
WHEN Item_Fat_Content IN ('LF','low fat') THEN 'LOW FAT'
WHEN Item_Fat_Content = 'reg' THEN 'Regular'
ELSE Item_Fat_Content
END

--Checking

SELECT DISTINCT (Item_Fat_Content)
FROM 
Blinkit_data

--FINDING THE TOTAL SALES OF BLINKIT IN MILLIONS(KPI'S)

SELECT 
CAST (SUM(Total_Sales)/1000000 AS DECIMAL (10,2)) AS TOTAL_SALES_BLINKIT_IN_MILLIONS
from Blinkit_data

--FINDING TOTAL SALES FOR LOW FAT ITEMS(KPI'S)

SELECT 
CAST (SUM(Total_Sales)/1000000 AS DECIMAL (10,2)) AS TOTAL_SALES_BLINKIT_LOW_FAT
from Blinkit_data
WHERE Item_Fat_Content = 'LOW FAT'

--FINDING TOTAL SALES FOR REGULAR ITEMS(KPI'S)

SELECT 
CAST (SUM(Total_Sales)/1000000 AS DECIMAL (10,2)) AS TOTAL_SALES_BLINKIT_REGULAR
from Blinkit_data
WHERE Item_Fat_Content = 'Regular'


--FINDING THE AVG SALES OF BLINKIT (KPI'S)

SELECT 
CAST (AVG (Total_Sales) AS DECIMAL (10,1)) AS AVG_SALES
from Blinkit_data

--FINDING TOTAL NO OF ITEMS WERE SOLD(KPI'S)

SELECT count(*) AS NO_OF_ITEMS_SOLD
FROM
Blinkit_data
WHERE Outlet_Establishment_Year= 2022

--FINDING AVG RATING(KPI'S)

SELECT CAST (AVG(Rating)AS DECIMAL (10,2)) AS AVG_RATING 
FROM
Blinkit_data

--GRANULAR  REQUIREMENTS

SELECT Item_Fat_Content,
CAST (SUM(Total_Sales)/1000 AS DECIMAL (10,2)) AS TOTAL_SALES_BLINKIT_IN_THOUSANDS,
CAST (AVG (Total_Sales) AS DECIMAL (10,1)) AS AVG_SALES,
CAST (AVG(Rating)AS DECIMAL (10,2)) AS AVG_RATING, 
COUNT(*) AS NO_OF_ITEMS_SOLD
FROM
Blinkit_data
GROUP BY Item_Fat_Content
ORDER BY TOTAL_SALES_BLINKIT_IN_THOUSANDS DESC

--PRODUCT WISE LOW PERFORMING ITEMS
SELECT TOP 5 Item_Type,
CAST (SUM(Total_Sales) AS DECIMAL (10,2)) AS TOTAL_SALES_BLINKIT,
CAST (AVG (Total_Sales) AS DECIMAL (10,1)) AS AVG_SALES,
CAST (AVG(Rating)AS DECIMAL (10,2)) AS AVG_RATING, 
COUNT(*) AS NO_OF_ITEMS_SOLD
FROM
Blinkit_data
GROUP BY Item_Type
ORDER BY TOTAL_SALES_BLINKIT ASC

--FINDING SALES BY OUTLET ESTABLISHMEMT YEAR

SELECT Outlet_Establishment_Year,
CAST (SUM(Total_Sales) AS DECIMAL(10,2)) AS TOTAL_SALES_BLINKIT,
CAST (AVG (Total_Sales) AS DECIMAL (10,1)) AS AVG_SALES,
CAST (AVG(Rating)AS DECIMAL (10,2)) AS AVG_RATING, 
COUNT(*) AS NO_OF_ITEMS_SOLD
FROM Blinkit_data
GROUP BY Outlet_Establishment_Year
ORDER BY TOTAL_SALES_BLINKIT DESC

--FINDING OUTLET WISE SALES PERCENTAGE

SELECT Outlet_Size,
CAST(SUM(Total_Sales) AS DECIMAL (10,2)) AS TOTAL_SALES,
CAST((SUM(Total_Sales)*100.0/SUM(SUM(Total_Sales))OVER()) AS DECIMAL(10,2)) AS SALES_PERCENTAGE
FROM Blinkit_data
GROUP BY Outlet_Size
ORDER BY TOTAL_SALES DESC

--FINDING TOTAL SALES BY TIER 

SELECT Outlet_Location_Type,
CAST (SUM(Total_Sales) AS DECIMAL(10,2)) AS TOTAL_SALES_BLINKIT,
CAST((SUM(Total_Sales)*100.0/SUM(SUM(Total_Sales))OVER()) AS DECIMAL(10,2)) AS SALES_PERCENTAGE,
CAST (AVG (Total_Sales) AS DECIMAL (10,1)) AS AVG_SALES,
CAST (AVG(Rating)AS DECIMAL (10,2)) AS AVG_RATING, 
COUNT(*) AS NO_OF_ITEMS_SOLD
FROM Blinkit_data
GROUP BY Outlet_Location_Type
ORDER BY TOTAL_SALES_BLINKIT DESC

--FINDING SALES FOR OUTLET TYPE
SELECT Outlet_Type,
CAST (SUM(Total_Sales) AS DECIMAL(10,2)) AS TOTAL_SALES_BLINKIT,
CAST((SUM(Total_Sales)*100.0/SUM(SUM(Total_Sales))OVER()) AS DECIMAL(10,2)) AS SALES_PERCENTAGE,
CAST (AVG (Total_Sales) AS DECIMAL (10,1)) AS AVG_SALES,
CAST (AVG(Rating)AS DECIMAL (10,2)) AS AVG_RATING, 
COUNT(*) AS NO_OF_ITEMS_SOLD
FROM Blinkit_data
GROUP BY Outlet_Type
ORDER BY TOTAL_SALES_BLINKIT DESC
