# -*- coding: utf-8 -*-
"""chronic disease project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwuuAsvjb-nc8dZV7crykwACs13ELuXE
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/kidney_disease.csv")
print(df)

print(df.to_string())

df.info()

df.describe()

df.shape

df.isnull().sum()

df.duplicated().sum()

df.rename(columns={"bp":"blood_pressure","sg":"specific_gravity","al":"almubin","su":"sugar","rbc":"red_blood_cells","pc":"plus_cells","pcc":"plus_cells_pumps","ba":"bacteria","bgr":"blood_glucose_random"}, inplace=True)

df.columns

df.rename(columns={"bu":"blood_urea","sc":"creatine","sod":"sodium","pot":"potasium","hemo":"hemoglobin"},inplace=True)

df.rename(columns={"pcv":"packed_cell_volume","wc":"white_blood_cells_count","rc":"red_blood_cells_count","htn":"hypertension","dm":"diabetes_melinus","cad":"c_artery_disease","appet":"appettite","pe":"poda_odema","ane":"anemia"},inplace = True)

df

columns=['packed_cell_volume','white_blood_cells_count','red_blood_cells_count']
df[columns]= df[columns].apply(pd.to_numeric,errors='coerce')

df.info()

df.isnull().sum()

for col in df.columns:
  if df[col].dtype=='object':
      df[col].fillna(df[col].mode()[0],inplace=True)
  else:
      df[col].fillna(df[col].mean(),inplace=True)

df.isnull().sum()

df['diabetes_melinus'].unique()

df['c_artery_disease'].unique()

df['classification'].unique()

df['diabetes_melinus']=df['diabetes_melinus'].replace({' yes':'yes','\tno':'no','\tyes':'yes'})

df['c_artery_disease']=df['c_artery_disease'].replace({'\tno':'no'})

df['classification']=df['classification'].replace({'ckd\t':'ckd'})

df['classification'].unique()

df['classification'] = df['classification'].map({'ckd': 1, 'notckd': 0})
df['red_blood_cells'] = df['red_blood_cells'].map({'normal': 1, 'abnormal': 0})
df['plus_cells'] = df['plus_cells'].map({'normal': 1, 'abnormal': 0})
df['plus_cells_pumps'] = df['plus_cells_pumps'].map({'present': 1, 'notpresent': 0})
df['bacteria'] = df['bacteria'].map({'present': 1, 'notpresent': 0})
df['hypertension'] = df['hypertension'].map({'yes': 1, 'no': 0})
df['diabetes_melinus'] = df['diabetes_melinus'].map({'yes': 1, 'no': 0})
df['c_artery_disease'] = df['c_artery_disease'].map({'yes': 1, 'no': 0})
df['appettite'] = df['appettite'].map({'good': 1, 'poor': 0})
df['poda_odema'] = df['poda_odema'].map({'yes': 1, 'no': 0})
df['anemia'] = df['anemia'].map({'yes': 1, 'no': 0})

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15,8))
sns.heatmap(df.corr(),annot=True)
plt.show()

target_corr=df.corr()['classification'].abs().sort_values(ascending=False)
target_corr

df['classification'].value_counts()

from sklearn.model_selection import train_test_split

x= df.drop('classification',axis=1)
y=df['classification']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

x_test.shape
x_train.shape

from sklearn.tree import DecisionTreeClassifier

dct = DecisionTreeClassifier()

dct.fit(x_train,y_train)

y_pred=dct.predict(x_test)
y_pred

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score,precision_score,recall_score

print(confusion_matrix(y_test,y_pred))

print(accuracy_score(y_test,y_pred))

print(precision_score(y_test,y_pred))

print(f1_score(y_test,y_pred))

print(recall_score(y_test,y_pred))

print(classification_report(y_test,y_pred))

from sklearn.svm import SVC

svc=SVC(kernel='linear')

svc.fit(x_train,y_train)

y_pred=svc.predict(x_test)
y_pred

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))