# -*- coding: utf-8 -*-
"""Copy of rollercoster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzpKLciVvaAupoveDJc1lvkRs2GlfdgH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/sample_data/coaster_db.csv')
print(df)

df.shape
df.head(5)
df.columns
df.dtypes

df.describe()

df= df[['coaster_name',
    #'Length', 'Speed',
    'Location', 'Status',
    #'Opening date',
     #  'Type',
    'Manufacturer',
    #'Height restriction', 'Model', 'Height',
     #  'Inversions', 'Lift/launch system', 'Cost', 'Trains', 'Park section',
      # 'Duration', 'Capacity', 'G-force', 'Designer', 'Max vertical angle',
     #  'Drop', 'Soft opening date', 'Fast Lane available', 'Replaced',
      # 'Track layout', 'Fastrack available', 'Soft opening date.1',
     #  'Closing date',
    'Opened',
    #'Replaced by', 'Website',
      # 'Flash Pass Available', 'Must transfer from wheelchair', 'Theme',
      # 'Single rider line available', 'Restraint Style',
       #'Flash Pass available', 'Acceleration', 'Restraints', 'Name',
       'year_introduced', 'latitude', 'longitude', 'Type_Main',
       'opening_date_clean',
    #'speed1', 'speed2', 'speed1_value', 'speed1_unit',
       'speed_mph',
    #'height_value', 'height_unit',
    'height_ft',
       'Inversions_clean', 'Gforce_clean']].copy()

df.shape
df.columns
df.describe()
df.dtypes

df['opening_date_clean']= pd.to_datetime(df['opening_date_clean'])
df['opening_date_clean']

df.columns

df= df.rename(columns={'coaster_name':'Coaster_Name',
                  'year_introduced':'Year_Introduced'})
df.columns

df.loc[df.duplicated()]
df.loc[df.duplicated(subset=['Coaster_Name'])]
df.query('Coaster_Name=="Derby Racer"')
df.loc[~df.duplicated(subset=['Coaster_Name','Location','opening_date_clean'])].reset_index(drop=True)
df= df.loc[~df.duplicated(subset=['Coaster_Name','Location','opening_date_clean'])].reset_index(drop=True).copy()

df.shape

df.columns

barplot=df['Year_Introduced'].value_counts().head(10)
plt.figure(figsize=(12,8))
sns.barplot(x=barplot.index,y=barplot,palette='rocket',hue=barplot.index)
plt.title('Top 10 Years Coasters Introduced')
plt.xlabel('Year Introduced')
plt.ylabel('Count')
plt.show()

sns.histplot(df['speed_mph'],kde=True,bins=20,color='black',label='speed_mph')
plt.title('Distribution of Coasters by Speed')
plt.xlabel('Speed (mph)')
plt.ylabel('Count')
plt.legend()
plt.show()

type_counts = df['Type_Main'].value_counts()
plt.figure(figsize=(6,6))
plt.pie(type_counts, labels=type_counts.index, autopct='%1.1f%%', colors=plt.cm.Paired.colors)
plt.title("Proportion of Coaster Types (Filtered)")
plt.show()

sns.kdeplot(df['speed_mph'],color='yellow')
plt.title('Distribution of Coasters by Speed')
plt.xlabel('Speed (mph)')
plt.ylabel('Count')
plt.show()

sns.boxplot(df[['longitude','latitude']],palette='rocket')
plt.title('Distribution of Coasters by Latitude')
plt.xlabel('Latitude')
plt.show()

sns.scatterplot(x=df['speed_mph'],y=df['height_ft'],color='blue')
plt.title('Speed vs Height')
plt.xlabel('Speed (mph)')
plt.ylabel('Height (ft)')
plt.show()

sns.pairplot(df[['speed_mph','height_ft','Year_Introduced','Gforce_clean']])
plt.show()

corr_matrix=df[['speed_mph','height_ft','Year_Introduced','Gforce_clean']].dropna().corr()
print(corr_matrix)
sns.heatmap(corr_matrix,annot=True,cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()
